

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
} from '@clerk/nextjs'
import { QueryProviders } from "@/providers/query-providers";
import SheetProviders from "@/providers/sheetProviders";
import { Toaster } from "@/components/ui/sonner";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
      <html lang="en">
        
        <body className={inter.className}>
          <QueryProviders>
            <SheetProviders/>
            <Toaster/>
            <Suspense fallback={<div>Loading...</div>}>
              {children}
            </Suspense>
            
          </QueryProviders>
            
        
        </body>
      </html>
    </ClerkProvider>
  );
}
